### ISSUE TITLE
Collect/calculate additional statistics

### ISSUE THREAD

**Issue by johnmhoran** [nexB/deltacode#5]
From @majurg  We can get basic counts currently in deltacode; we need to expand that to additional calculations like % added, removed, etc, % changed, perhaps some sort of codebase 'drift' calculation that incorporates a number of different stats.

**Comment by arnav-mandal1234** [comment]
Can I work on this? @johnmhoran @majurg @pombredanne

**Comment by steven-esser** [comment]
@arnav-mandal1234 sure

**Comment by arnav-mandal1234** [comment]
@majurg @pombredanne @mjherzog @johnmhoran after going through the whole discussion above, I think we should make all the percentage variables with the base of count(old_files). This is because our basic idea is used to compare old to new. So, generally, users would like to see what changes have been made to new_directory as compared to old_directory. What are your opinions?

Please guide me if I am wrong.

**Comment by steven-esser** [comment]
@arnav-mandal1234 Yes, you are correct. We would want the base to be `count(old_files)` for these calculations. If the `new` directory has many more files added, percentages will be `> 100%`, but I think that is what we want to see anyway.

**Comment by arnav-mandal1234** [comment]
@majurg Yes, since our sample space is not limited, I mean the sample space is infinite for the addition of files. So, >100% is likely to happen. 
I would make a PR tonight. :)

**Comment by arnav-mandal1234** [comment]
@majurg This can be done in many ways.
I selected this approach:
1) make a class "stats" in __init__.py just like a Delta class
2) Then will initialize the object of stat class in DeltaCode class
3) proceed to make the following changes.

Is that okay?

**Comment by steven-esser** [comment]
@arnav-mandal1234 yes that it ok
